# 文件
file:
  file-path: D:/file/files/
  big-file-path: D:/file/files/big/
  # 存储图片资源的目录
  img-path: D:/file/files/img/
  template-path: D:/file/files/template/
  zip-path: D:/file/files/zip/
spring:
  servlet:
    multipart:
      # 开启文件上传
      enabled: true
      # 单个文件上传大小
      max-file-size: 100MB
      # 设置总上传大小
      max-request-size: 200MB
