logging:
  config: classpath:logback-custom.xml
  level:
    root: debug
  path: applog/bbs
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    # 开发
    url: jdbc:mysql://localhost:3306/fleet-bbs?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    initialSize: 1
    minIdle: 1
    maxIdle: 20
    maxActive: 50
    maxWait: 60000
    logAbandoned: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    validationQuery: select 'x'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#mybatis:
#  type-aliases-package: com.fleet.user.entity
#  mapper-locations: mybatis/**/*Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
