/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator;


import com.fleet.jooq.generator.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FleetTest extends SchemaImpl {

    private static final long serialVersionUID = 70222779;

    /**
     * The reference instance of <code>fleet-test</code>
     */
    public static final FleetTest FLEET_TEST = new FleetTest();

    /**
     * The table <code>fleet-test.user</code>.
     */
    public final User USER = com.fleet.jooq.generator.tables.User.USER;

    /**
     * No further instances allowed
     */
    private FleetTest() {
        super("fleet-test", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
