/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator;


import com.fleet.jooq.generator.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in fleet-test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>fleet-test.user</code>.
     */
    public static final User USER = com.fleet.jooq.generator.tables.User.USER;
}
