spring:
  application:
    name: service-provider
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 # 定义服务续约任务（心跳）的调用间隔，单位：秒
    lease-expiration-duration-in-seconds: 60 # 定义服务失效的时间，单位：秒
