spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fleet-test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password:
    # 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 3
      # 最小连接池数量
      min-idle: 3
      # 最大连接池数量
      max-active: 18
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的 sql ，要求是一个查询语句
      validation-query: SELECT 1 FROM dual
      # 建议配置为 true ，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis ，执行 validationQuery 检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存 preparedStatement ，也就是 PSCache 。PSCache 对支持游标的数据库性能提升巨大，比如说 oracle 。在 mysql 下建议关闭。
      pool-prepared-statements: false
      # 要启用 PSCache ，必须配置大于0，当大于0时，poolPreparedStatements 自动触发修改为 true。
      max-pool-prepared-statement-per-connection-size: 50
      # 配置监控统计拦截的 filters，去掉后监控界面sql无法统计
      filters: stat,wall,log4j2
      # 通过 connectProperties 属性来打开 mergeSql 功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个 DruidDataSource 的监控数据
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        #        allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        #        deny: 192.168.1.73
        #  是否启用HTML页面上的“Reset All”功能
        reset-enable: true
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
mybatis:
  mapper-locations: mybatis/*Mapper.xml
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
